# Generated by Django 2.2.7 on 2019-12-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191204_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='exposed_sequence',
        ),
        migrations.RemoveField(
            model_name='news',
            name='main_key_word',
        ),
    ]
