# Generated by Django 2.2.7 on 2019-12-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191207_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
