# Generated by Django 2.2.7 on 2019-12-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191207_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('-count', 'name')},
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='KeyWordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('key_from', models.ManyToManyField(to='backend.News')),
            ],
            options={
                'ordering': ('-count', 'name'),
            },
        ),
    ]
