# Generated by Django 2.2.7 on 2019-12-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191208_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordhistory',
            name='date',
            field=models.CharField(max_length=16),
        ),
    ]
