# Generated by Django 2.2.7 on 2019-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191208_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
