# Generated by Django 2.2.7 on 2019-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20191208_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
